apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: robotshop/rs-web:latest
        name: web
        ports:
        - containerPort: 8080
        env:
        - name: INSTANA_EUM_KEY
          value: "JOIUz3kPTtOy1FLFhSFgVA"
        - name: INSTANA_EUM_REPORTING_URL
          value: "https://eum-us-west-2.instana.io"
      restartPolicy: Always
status: {}
