apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #TODO: provide object a name name called mysqlpvc
  labels:
    run: gowebapp-mysql
spec:
  #TODO: define accessModes
  - ReadWriteOnce
  resources:
    requests:
      #TODO: request 1Gi of storage
